[linters]
enable = [
    "asciicheck",
    "bodyclose",
    "cyclop",
    "deadcode",
    # "depguard",
    "dogsled",
    "dupl",
    "durationcheck",
    "errcheck",
    "errorlint",
    "exportloopref",
    "exhaustive",
    "forbidigo",
    "forcetypeassert",
    # "funlen",
    "gci",
    "gochecknoglobals",
    "gochecknoinits",
    "gocognit",
    "goconst",
    "gocritic",
    "gocyclo",
    "godot",
    # "godox",
    "goerr113",
    # "gomnd",
    "goprintffuncname",
    "gosec",
    "gosimple",
    "govet",
    "ifshort",
    "importas",
    "ineffassign",
    "lll",
    "makezero",
    "misspell",
    "nakedret",
    "nestif",
    "nilerr",
    "nlreturn",
    "noctx",
    "nolintlint",
    "prealloc",
    "predeclared",
    # "rowserrcheck",
    # "sqlclosecheck",
    "staticcheck",
    "structcheck",
    "stylecheck",
    "testpackage",
    "typecheck",
    "unconvert",
    "unparam",
    "unused",
    "varcheck",
    "wastedassign",
    "whitespace",
    # "wrapcheck",
    # "wsl"
    ]

[issues]
fix = true
max-issues-per-linter = 0
max-same-issues = 0

exclude = [
    "`automato` is a misspelling of `automation`",
    "do not define dynamic errors, use wrapped static errors instead"
]

    [[issues.exclude-rules]]
    path = "_test\\.go"
    linters = [
        "dupl",
        "errcheck",
        "forcetypeassert",
        "gocyclo",
        "gosec"
    ]

[linters-settings]
    [linters-settings.gci]
        sections = [
            "standard",
            "default",
            "prefix(github.com/meanguy/automato)"
        ]
        section-separators = ["newLine"]
    [linters-settings.nolintlint]
        allow-leading-space = false
        allow-unused = false
        require-explanation = true
        require-specific = true
